/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseInfo: typeof import('./components/left/BaseInfo.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    Duty: typeof import('./components/right/duty.vue')['default']
    DutyPopup: typeof import('./components/middle/duty-popup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Event: typeof import('./components/right/event.vue')['default']
    Head: typeof import('./components/head.vue')['default']
    InformationSafety: typeof import('./components/left/informationSafety.vue')['default']
    IotCenter: typeof import('./components/middle/IotCenter.vue')['default']
    IotLeft: typeof import('./components/left/IotLeft.vue')['default']
    IotRight: typeof import('./components/right/IotRight.vue')['default']
    Left: typeof import('./components/left/index.vue')['default']
    List: typeof import('./components/list.vue')['default']
    Map: typeof import('./components/middle/map.vue')['default']
    Middle: typeof import('./components/middle/index.vue')['default']
    Pie: typeof import('./components/right/pie.vue')['default']
    Population: typeof import('./components/left/Population.vue')['default']
    Popup: typeof import('./components/popup.vue')['default']
    Power: typeof import('./components/right/power.vue')['default']
    Public: typeof import('./components/left/Public.vue')['default']
    Right: typeof import('./components/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPlay: typeof import('./components/right/scroll-play.vue')['default']
    Transfer: typeof import('./components/middle/transfer.vue')['default']
    TwinCenter: typeof import('./components/middle/TwinCenter.vue')['default']
    TwinLeft: typeof import('./components/left/TwinLeft.vue')['default']
    TwinRight: typeof import('./components/right/TwinRight.vue')['default']
    VideoPopup: typeof import('./components/middle/video-popup.vue')['default']
    Weather: typeof import('./components/right/weather.vue')['default']
    WeatherInfo: typeof import('./components/left/WeatherInfo.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
